models:
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\CumqueQui:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NullaAnimi:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuoUt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AutSaepe:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\TemporaEt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EumNisi:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EumEt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EstUllam:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\RemSequi:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ArchitectoDolore:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EaAut:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\OditAut:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\FugaCorrupti:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VoluptatemAut:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AutSimilique:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NostrumFacilis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\UtAut:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DucimusMaiores:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\PraesentiumPerferendis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SuntIn:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\LiberoTotam:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EnimQui:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\IdQuasi:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\PerspiciatisEst:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EtImpedit:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AspernaturIste:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AtQuae:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EiusOfficia:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\RerumFacilis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EosConsequuntur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\MinimaPariatur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuiaAtque:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EiusFuga:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\RepellendusLaboriosam:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SequiVitae:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\OfficiaDeleniti:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\LaudantiumId:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\TemporaQuae:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NullaEst:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuibusdamQuo:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AutemNihil:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\OptioEveniet:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EstSed:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SintRepellat:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuisquamEst:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuiIn:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuasiDucimus:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EtRecusandae:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EstVeritatis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SedNon:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DeseruntVel:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EtNemo:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AtEius:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ConsequaturOfficiis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\BeataeFuga:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VoluptasMollitia:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuodBlanditiis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\TotamQuas:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DoloresNam:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\IpsamNulla:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VelitA:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NonDignissimos:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\TeneturVelit:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EaqueId:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AdipisciSit:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\MolestiaeQui:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\TemporibusConsequuntur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NonIn:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\OmnisMolestiae:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\CumqueLabore:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AliquidEveniet:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\IsteEaque:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EsseUt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SintQuia:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AtqueEt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NobisDolor:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AutEveniet:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\LiberoNesciunt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DictaUt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\MinimaNemo:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EtEa:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\OptioEum:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\TemporeBeatae:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AnimiEst:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AutA:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ErrorEaque:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ReprehenderitEveniet:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\CupiditateEum:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EaTenetur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuiNobis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AutQui:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\HarumNon:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\IpsumSaepe:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SaepeMagnam:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SaepeEt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NequeIn:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AutFugit:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ArchitectoTotam:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuiLaboriosam:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\UtAb:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SedMolestiae:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuiVeniam:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SuntError:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\LaudantiumRerum:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AutQuis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DoloremAsperiores:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AliquidMagni:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\CorporisPorro:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NihilNesciunt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VeroDolorem:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\FacereLaborum:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\OditPerspiciatis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\RepellatIusto:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\CumqueCommodi:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DoloresSed:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EosSaepe:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\RecusandaeQuia:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\MollitiaQuis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\UllamNihil:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AperiamNisi:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ExQuaerat:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\RerumSoluta:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SuntEa:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SitConsequatur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\TotamVoluptatem:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NisiVoluptates:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\PerspiciatisEt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VoluptasAd:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EtAb:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\OfficiaEt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\PerspiciatisMinima:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AperiamError:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AtAutem:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SitCumque:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\InDolorum:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VelDebitis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\PossimusFuga:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EsseSed:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DoloresSint:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\RecusandaeQui:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ExplicaboRepellat:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuisTempore:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VoluptatibusNisi:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ModiAut:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DelenitiItaque:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NihilIllo:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\OfficiaPerferendis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AmetOccaecati:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\IdUt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AbLaudantium:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SolutaVitae:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuisProvident:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\FugitNihil:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuosVoluptatem:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EstNon:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AccusamusTenetur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ModiVel:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\OmnisDebitis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VoluptatemNon:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\LaborumImpedit:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SedEt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DelectusEst:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\OfficiisEa:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SuscipitPraesentium:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\UtNon:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\MolestiaeDolorum:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VelitAut:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuibusdamDolores:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VeniamCommodi:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\UtOccaecati:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\FacilisConsequuntur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VoluptatesMollitia:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AccusantiumAut:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ConsequunturEt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuiDolorem:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SedAtque:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NumquamConsequatur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ReiciendisSunt:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EumNulla:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EtBlanditiis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuiIpsa:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DoloresDistinctio:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VitaeRepellat:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DelenitiEsse:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VoluptatemMinus:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VeritatisMollitia:
    operations: '*'
    fields: '*'
