models:
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VoluptasQuiDistinctio:
    operations: '*'
    fields:
      id: true
      aStringValue: true
      numeric: true
      trueOrFalse: true
      myNovel: true
      myNovelWithFormattedContent: true
      showMeTheMoney: true
      listOfThings: true
      yourTimeWillCome: true
      splintingNumber: true
      inTheYearOfThyLord: true
      voluptasQuiDistinctio: true
      voluptasQuiDistinctios: true
      accusantiumExercitationemDolor: true
      accusantiumExercitationemDolors: true
      cumQuiDebitis: true
      cumQuiDebitiss: true
      eosVoluptasPossimus: true
      eosVoluptasPossimuss: true
      isteSitFugit: true
      isteSitFugits: true
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AccusantiumExercitationemDolor:
    operations: '*'
    fields:
      id: true
      aStringValue: true
      numeric: true
      trueOrFalse: true
      myNovel: true
      myNovelWithFormattedContent: true
      showMeTheMoney: true
      listOfThings: true
      yourTimeWillCome: true
      splintingNumber: true
      inTheYearOfThyLord: true
      voluptasQuiDistinctio: true
      voluptasQuiDistinctios: true
      accusantiumExercitationemDolor: true
      accusantiumExercitationemDolors: true
      cumQuiDebitis: true
      cumQuiDebitiss: true
      eosVoluptasPossimus: true
      eosVoluptasPossimuss: true
      isteSitFugit: true
      isteSitFugits: true
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\CumQuiDebitis:
    operations: '*'
    fields:
      id: true
      aStringValue: true
      numeric: true
      trueOrFalse: true
      myNovel: true
      myNovelWithFormattedContent: true
      showMeTheMoney: true
      listOfThings: true
      yourTimeWillCome: true
      splintingNumber: true
      inTheYearOfThyLord: true
      voluptasQuiDistinctio: true
      voluptasQuiDistinctios: true
      accusantiumExercitationemDolor: true
      accusantiumExercitationemDolors: true
      cumQuiDebitis: true
      cumQuiDebitiss: true
      eosVoluptasPossimus: true
      eosVoluptasPossimuss: true
      isteSitFugit: true
      isteSitFugits: true
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\EosVoluptasPossimus:
    operations: '*'
    fields:
      id: true
      aStringValue: true
      numeric: true
      trueOrFalse: true
      myNovel: true
      myNovelWithFormattedContent: true
      showMeTheMoney: true
      listOfThings: true
      yourTimeWillCome: true
      splintingNumber: true
      inTheYearOfThyLord: true
      voluptasQuiDistinctio: true
      voluptasQuiDistinctios: true
      accusantiumExercitationemDolor: true
      accusantiumExercitationemDolors: true
      cumQuiDebitis: true
      cumQuiDebitiss: true
      eosVoluptasPossimus: true
      eosVoluptasPossimuss: true
      isteSitFugit: true
      isteSitFugits: true
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\IsteSitFugit:
    operations: '*'
    fields:
      id: true
      aStringValue: true
      numeric: true
      trueOrFalse: true
      myNovel: true
      myNovelWithFormattedContent: true
      showMeTheMoney: true
      listOfThings: true
      yourTimeWillCome: true
      splintingNumber: true
      inTheYearOfThyLord: true
      voluptasQuiDistinctio: true
      voluptasQuiDistinctios: true
      accusantiumExercitationemDolor: true
      accusantiumExercitationemDolors: true
      cumQuiDebitis: true
      cumQuiDebitiss: true
      eosVoluptasPossimus: true
      eosVoluptasPossimuss: true
      isteSitFugit: true
      isteSitFugits: true
