models:
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuidemConsequuntur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SapienteAlias:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\RecusandaeQui:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\RerumQuae:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NobisVeniam:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\PerspiciatisEst:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\InventoreVoluptas:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuiHic:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\RepellatDolorum:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SolutaOfficia:
    operations: '*'
    fields: '*'
