models:
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DoloreTenetur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AnimiNihil:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\MagniDolores:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SedDelectus:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\PorroRem:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\DistinctioId:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AliasQuis:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SequiQuia:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\NamConsequatur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\OdioIusto:
    operations: '*'
    fields: '*'
