models:
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuaeQuiaConsequatur:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VelitOmnisEos:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\UtAutTotam:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\ReprehenderitBlanditiisQuos:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\SequiVoluptatesAccusamus:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\AutNihilDolores:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\QuiVoluptatemSed:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\VoluptatumIpsaSaepe:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\TemporaCorporisDistinctio:
    operations: '*'
    fields: '*'
  MaximeRainville\SilverStripeGraphQLBenchmark\Models\RecusandaeEtAt:
    operations: '*'
    fields: '*'
